### ISSUE TITLE
Nested struct/cell with compression ?

### ISSUE THREAD

**Issue by tbeu** [NJannasch/matio-examples#3]
There was a review comment on sf.net almost six months ago:

> One cannot write structs or nested cell arrays to files when using ZLIB compression.

Can you please give examples for both cases. Thanks a lot for your efforts! I really appreciate this.

**Comment by NJannasch** [comment]
The example contains one struct which contains other structs and cells.
[nestedStructsAndCells.cpp](https://github.com/NJannasch/matio-examples/blob/master/Examples/nestedStructsAndCells.cpp) / 51ce1e183821a2880c95f26aad13e74cf3e1fbaa

It's working for me without any problem.

**Comment by tbeu** [comment]
Thanks. I tested it also and they work as expected.

Note: I updated [matio](https://github.com/tbeu/matio) yesterday to finally fix the two critical issues of https://sourceforge.net/p/matio/bugs/29/.
