### ISSUE TITLE
N-dimensional array

### ISSUE THREAD

**Issue by tbeu** [NJannasch/matio-examples#4]
I would be interested how to save a 3D or 4D array to file, preferable v7.3 (=HDF5 based). Do you mind to give an example for these cases. Thanks a lot.

**Comment by NJannasch** [comment]
See [nDimensionalArray.cpp](https://github.com/NJannasch/matio-examples/blob/master/Examples/nDimensionalArray.cpp) / 33e1e4dd3579f49e2bb9c948f9aa91c619b516d9

Should work for v7.3, too.

**Comment by tbeu** [comment]
Thanks. Can you pls make dimension sizes unique numbers, not all 4. E.g., 3, 4, 5, 6. It is easier for debugging then if you know which dimension you are.

**Comment by NJannasch** [comment]
Done.

**Comment by tbeu** [comment]
Thanks. Going to test it.

**Comment by tbeu** [comment]
Yes, it is working! But example values of the arrays contain many zeros which could be improved.

**Comment by NJannasch** [comment]
Thanks for the advice.
I have updated the file
