### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by tbeu** [NJannasch/matio-examples#6]
Can you please add a simple Makefile (GCC). This would make it easier to run your examples in Travis CI of matio. Thanks.

**Comment by NJannasch** [comment]
Sure, i will add it until the weekend.
Am 12.04.2016 22:26 schrieb tbeu notifications@github.com:Can you please add a simple Makefile (GCC). This would make it easier to run your examples in Travis CI of matio. Thanks.

**Comment by NJannasch** [comment]
Makefile added with commit: e3990a302d7f45ad7fa40f07549312c11a0cf12b
