### ISSUE TITLE
an example for reading .mat file?

### ISSUE THREAD

**Issue by khavernathy** [NJannasch/matio-examples#8]
Would be fantastic

**Comment by khavernathy** [comment]
Found one here http://sourceforge.net/p/matio/discussion/609376/thread/9df1158c/

**Comment by tbeu** [comment]
See section 2.2 of the [user guide](https://bitbucket.org/tbeu/downloads/downloads/matio_user_guide.pdf).

**Comment by NJannasch** [comment]
@khavernathy Feel free to contribute an example :-)
